# ===== WinRM / Ansible =====
ansible_connection: winrm
ansible_user: Administrator
ansible_password: vagrant
ansible_port: 5985
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore

# ===== Active Directory =====
domain_name: ilove.flower
domain_netbios: FLOWER
safe_mode_password: "Azerty,123"

