- name: Test Linux connectivity
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Ping Linux
      ansible.builtin.ping:

- name: Test Windows connectivity
  hosts: windows
  gather_facts: false
  tasks:
    - name: Ping Windows
      ansible.windows.win_ping:
